name: Auto Merge Develop to Master and Publish to NPM

on:
  push:
    branches:
      - develop

jobs:
  auto-merge-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0 # 获取完整历史记录

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.8.1 # 设置 Node.js 版本为 20.8.1

      - name: Fetch master branch
        run: |
          git fetch origin master
          NEW_COMMITS=$(git rev-list --count origin/master..develop)
          echo "NEW_COMMITS:$NEW_COMMITS"
          echo "NEW_COMMITS=$NEW_COMMITS" >> $GITHUB_OUTPUT

      - name: Check version number
        id: check-version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          PRE_RELEASE_TAG=$(node -p "require('./package.json').version.split('-')[1] || ''")
          echo "VERSION:$VERSION"  
          echo "PRE_RELEASE_TAG:$PRE_RELEASE_TAG"  
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "PRE_RELEASE_TAG=$PRE_RELEASE_TAG" >> $GITHUB_OUTPUT

      - name: Get Author Information
        id: get-author
        run: |
          AUTHOR=$(node -p "require('./package.json').author")
          AUTHOR_NAME=$(node -p "typeof require('./package.json').author === 'object' ? require('./package.json').author.name : require('./package.json').author")
          AUTHOR_EMAIL=$(node -p "typeof require('./package.json').author === 'object' ? require('./package.json').author.email : ''")
          echo "AUTHOR_NAME:$AUTHOR_NAME"
          echo "AUTHOR_EMAIL:$AUTHOR_EMAIL"
          echo "AUTHOR_NAME=$AUTHOR_NAME" >> $GITHUB_OUTPUT
          echo "AUTHOR_EMAIL=$AUTHOR_EMAIL" >> $GITHUB_OUTPUT

      - name: Check for new tags
        id: check-tags
        run: |
          NEW_TAGS=$(git tag --points-at develop)
          echo "NEW_TAGS:$NEW_TAGS"
          echo "NEW_TAGS=$NEW_TAGS" >> $GITHUB_OUTPUT

      - name: Merge develop into master with squash
        if: steps.check-tags.outputs.NEW_TAGS != ''
        run: |
          git config --global user.email "${{ steps.get-author.outputs.AUTHOR_EMAIL }}"
          git config --global user.name "${{ steps.get-author.outputs.AUTHOR_NAME }}"
          git checkout master
          git merge develop --squash
          # 由于我们不再使用倒数第二个提交的信息作为提交消息，这里可以使用默认的提交消息或者从标签信息中获取。
          git commit -m "Merge develop into master with new tags: ${{ steps.check-tags.outputs.NEW_TAGS }}"
          git push origin master
          
      - name: Pull latest changes from remote master
        if: steps.check-tags.outputs.NEW_TAGS != ''
        run: |
          git checkout master
          git pull origin master --ff-only
          
      - name: Push to remote master after pulling
        if: steps.check-tags.outputs.NEW_TAGS != ''
        run: |
          git push origin master