name: Auto Merge Develop to Main

on:
  push:
    branches:
      - develop

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0 # 获取完整历史记录

      - name: Fetch main branch and check for new tags
        id: check-main-and-tags
        run: |
          git fetch origin main
          NEW_COMMITS=$(git rev-list --count origin/main..develop)
          echo "NEW_COMMITS:$NEW_COMMITS"
          echo "NEW_COMMITS=$NEW_COMMITS" >> $GITHUB_OUTPUT

          # 确保标签已存在于远程仓库
          NEW_TAGS=$(git ls-remote --tags origin | awk '{print $2}' | grep -E "^v1\.0\.[0-9]+$")
          echo "NEW_TAGS:$NEW_TAGS"
          echo "NEW_TAGS=$NEW_TAGS" >> $GITHUB_OUTPUT

      - name: Merge develop into main with squash
        if: steps.check-main-and-tags.outputs.NEW_TAGS != ''
        run: |
          git config --global user.email "657225485@qq.com"
          git config --global user.name "Frieda.Hu<657225485@qq.com>"
          git checkout main
          git merge develop --squash
          git commit -m "$(git log --pretty=format:'%B' -n 2 develop | tail -n +2 | tr -d '\n')"
          git push origin main